"""
Inspector Rabbit - Report Generator
Export OSINT findings to HTML, JSON, and PDF
"""

import json
import os
import datetime
from typing import Dict, List, Any
from pathlib import Path


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Inspector Rabbit OSINT Report - {title}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', Ubuntu, sans-serif; background: #0d1117; color: #c9d1d9; }}
  .header {{ background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
             padding: 40px; text-align: center; border-bottom: 2px solid #00f5ff; }}
  .header h1 {{ font-size: 2.5rem; color: #00f5ff; text-shadow: 0 0 20px rgba(0,245,255,0.5); }}
  .header .subtitle {{ color: #8b949e; margin-top: 8px; font-size: 0.95rem; }}
  .header .meta {{ display: flex; justify-content: center; gap: 30px; margin-top: 20px; }}
  .header .meta-item {{ background: rgba(255,255,255,0.05); border: 1px solid rgba(0,245,255,0.2);
                        padding: 8px 20px; border-radius: 20px; font-size: 0.85rem; }}
  .container {{ max-width: 1200px; margin: 0 auto; padding: 30px; }}
  .section {{ background: #161b22; border: 1px solid #21262d; border-radius: 12px;
              margin-bottom: 24px; overflow: hidden; }}
  .section-header {{ background: linear-gradient(90deg, #1f2937, #111827);
                     padding: 16px 24px; border-bottom: 1px solid #21262d;
                     display: flex; align-items: center; gap: 12px; }}
  .section-header h2 {{ color: #00f5ff; font-size: 1.1rem; }}
  .section-header .badge {{ background: #00f5ff22; border: 1px solid #00f5ff44;
                            color: #00f5ff; padding: 2px 10px; border-radius: 12px;
                            font-size: 0.75rem; }}
  .section-body {{ padding: 20px 24px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.875rem; }}
  th {{ background: #21262d; color: #8b949e; padding: 10px 14px; text-align: left;
        border-bottom: 1px solid #30363d; font-weight: 600; text-transform: uppercase;
        font-size: 0.75rem; letter-spacing: 0.5px; }}
  td {{ padding: 10px 14px; border-bottom: 1px solid #21262d; vertical-align: top; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover td {{ background: #1f2937; }}
  .found {{ color: #3fb950; }}
  .not-found {{ color: #8b949e; }}
  .status-found {{ background: #1a3a2a; color: #3fb950; padding: 2px 10px;
                   border-radius: 12px; font-size: 0.75rem; border: 1px solid #3fb95033; }}
  .status-not-found {{ background: #21262d; color: #8b949e; padding: 2px 10px;
                       border-radius: 12px; font-size: 0.75rem; }}
  .url-link {{ color: #58a6ff; text-decoration: none; }}
  .url-link:hover {{ text-decoration: underline; }}
  .tag {{ display: inline-block; background: #21262d; color: #8b949e; padding: 2px 8px;
          border-radius: 6px; font-size: 0.75rem; margin: 2px; }}
  .highlight {{ color: #e3b341; }}
  .danger {{ color: #f85149; }}
  .info {{ color: #58a6ff; }}
  .footer {{ text-align: center; padding: 30px; color: #484f58; font-size: 0.8rem; }}
  .stat-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 16px; }}
  .stat-card {{ background: #21262d; border-radius: 10px; padding: 20px; text-align: center;
               border: 1px solid #30363d; }}
  .stat-card .value {{ font-size: 2rem; font-weight: bold; color: #00f5ff; }}
  .stat-card .label {{ color: #8b949e; font-size: 0.8rem; margin-top: 4px; }}
  pre {{ background: #0d1117; padding: 16px; border-radius: 8px; overflow-x: auto;
        font-size: 0.8rem; border: 1px solid #21262d; white-space: pre-wrap; }}
</style>
</head>
<body>
<div class="header">
  <h1>🐇 Inspector Rabbit OSINT Report</h1>
  <div class="subtitle">Open Source Intelligence Report — Educational Use Only</div>
  <div class="meta">
    <div class="meta-item">Target: <strong>{title}</strong></div>
    <div class="meta-item">Generated: <strong>{timestamp}</strong></div>
    <div class="meta-item">Module: <strong>{module}</strong></div>
  </div>
</div>
<div class="container">
{content}
</div>
<div class="footer">
  Generated by Inspector Rabbit OSINT Tool &bull; For authorized educational use only &bull; {timestamp}
</div>
</body>
</html>
"""


def _make_table(headers: List[str], rows: List[List[str]]) -> str:
    th = ''.join(f'<th>{h}</th>' for h in headers)
    trs = ''
    for row in rows:
        tds = ''.join(f'<td>{cell}</td>' for cell in row)
        trs += f'<tr>{tds}</tr>'
    return f'<table><thead><tr>{th}</tr></thead><tbody>{trs}</tbody></table>'


def generate_username_report(username: str, results: list) -> str:
    found = [r for r in results if r.found]
    not_found = [r for r in results if not r.found and not r.error]
    errors = [r for r in results if r.error]

    stat_html = f'''
    <div class="stat-grid">
      <div class="stat-card"><div class="value">{len(results)}</div><div class="label">Sites Checked</div></div>
      <div class="stat-card"><div class="value" style="color:#3fb950">{len(found)}</div><div class="label">Profiles Found</div></div>
      <div class="stat-card"><div class="value">{len(not_found)}</div><div class="label">Not Found</div></div>
      <div class="stat-card"><div class="value" style="color:#f85149">{len(errors)}</div><div class="label">Errors</div></div>
    </div>
    '''

    rows = []
    for r in sorted(results, key=lambda x: (not x.found, x.site)):
        status = '<span class="status-found">FOUND</span>' if r.found else '<span class="status-not-found">NOT FOUND</span>'
        url = f'<a class="url-link" href="{r.url}" target="_blank">{r.url}</a>' if r.found else r.url
        err = f'<span style="color:#8b949e">{r.error}</span>' if r.error else ''
        rows.append([r.site, r.category, status, url, f'{r.response_time}ms', err])

    table = _make_table(['Site', 'Category', 'Status', 'URL', 'Response', 'Error'], rows)

    content = f'''
    <div class="section">
      <div class="section-header"><h2>Summary</h2><span class="badge">{len(found)} found</span></div>
      <div class="section-body">{stat_html}</div>
    </div>
    <div class="section">
      <div class="section-header"><h2>Results for @{username}</h2></div>
      <div class="section-body">{table}</div>
    </div>
    '''

    return HTML_TEMPLATE.format(
        title=f"@{username}",
        timestamp=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC'),
        module='Username Search',
        content=content
    )


def generate_domain_report(result) -> str:
    content = ""

    # WHOIS
    if result.whois:
        w = result.whois
        rows = [
            ['Registrar', w.registrar],
            ['Created', w.creation_date],
            ['Expires', w.expiration_date],
            ['Updated', w.updated_date],
            ['Registrant', w.registrant_name or w.registrant_org],
            ['Email', w.registrant_email],
            ['Country', w.registrant_country],
            ['Status', ', '.join(w.status[:3])],
            ['Name Servers', '<br>'.join(w.name_servers[:4])],
        ]
        content += f'''
        <div class="section">
          <div class="section-header"><h2>WHOIS Information</h2></div>
          <div class="section-body">{_make_table(['Field', 'Value'], rows)}</div>
        </div>'''

    # DNS Records
    if result.dns_records:
        rows = [[r.record_type, f'<code>{r.value}</code>', str(r.ttl)] for r in result.dns_records]
        content += f'''
        <div class="section">
          <div class="section-header"><h2>DNS Records</h2><span class="badge">{len(result.dns_records)}</span></div>
          <div class="section-body">{_make_table(['Type', 'Value', 'TTL'], rows)}</div>
        </div>'''

    # SSL
    if result.ssl_info:
        s = result.ssl_info
        if not s.error:
            rows = [
                ['Subject', str(s.subject)],
                ['Issuer', str(s.issuer)],
                ['Valid From', s.not_before],
                ['Valid Until', s.not_after],
                ['SANs', '<br>'.join(s.san[:10])],
                ['Serial', s.serial_number],
            ]
            content += f'''
            <div class="section">
              <div class="section-header"><h2>SSL Certificate</h2></div>
              <div class="section-body">{_make_table(['Field', 'Value'], rows)}</div>
            </div>'''

    # Subdomains
    if result.subdomains:
        rows = [[sub] for sub in sorted(result.subdomains)]
        content += f'''
        <div class="section">
          <div class="section-header"><h2>Subdomains</h2><span class="badge">{len(result.subdomains)}</span></div>
          <div class="section-body">{_make_table(['Subdomain'], rows)}</div>
        </div>'''

    # Technologies
    if result.technologies:
        tags = ''.join(f'<span class="tag">{t}</span>' for t in result.technologies)
        content += f'''
        <div class="section">
          <div class="section-header"><h2>Detected Technologies</h2></div>
          <div class="section-body">{tags}</div>
        </div>'''

    return HTML_TEMPLATE.format(
        title=result.domain,
        timestamp=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC'),
        module='Domain Intelligence',
        content=content
    )


def save_json_report(data: Any, filepath: str) -> str:
    def default_handler(obj):
        if hasattr(obj, '__dict__'):
            return obj.__dict__
        if isinstance(obj, set):
            return list(obj)
        return str(obj)

    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2, default=default_handler)
    return filepath


def save_html_report(html: str, filepath: str) -> str:
    with open(filepath, 'w') as f:
        f.write(html)
    return filepath


def generate_pdf_report(html: str, filepath: str) -> str:
    """Convert HTML report to PDF using reportlab fallback"""
    try:
        from reportlab.lib.pagesizes import letter, A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
        from bs4 import BeautifulSoup

        soup = BeautifulSoup(html, 'lxml')
        doc = SimpleDocTemplate(filepath, pagesize=A4,
                                 rightMargin=0.75*inch, leftMargin=0.75*inch,
                                 topMargin=0.75*inch, bottomMargin=0.75*inch)

        styles = getSampleStyleSheet()
        story = []

        title_style = ParagraphStyle('Title', parent=styles['Title'],
                                      fontSize=20, textColor=colors.HexColor('#00f5ff'),
                                      spaceAfter=12)
        heading_style = ParagraphStyle('Heading', parent=styles['Heading2'],
                                       fontSize=13, textColor=colors.HexColor('#58a6ff'),
                                       spaceAfter=8, spaceBefore=16)
        normal_style = ParagraphStyle('Normal', parent=styles['Normal'],
                                      fontSize=9, textColor=colors.HexColor('#c9d1d9'),
                                      spaceAfter=4)

        story.append(Paragraph("🐇 Inspector Rabbit OSINT Report", title_style))
        story.append(Spacer(1, 0.2*inch))
        story.append(Paragraph(
            f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            normal_style
        ))
        story.append(Spacer(1, 0.3*inch))

        # Extract text content
        for section in soup.select('.section'):
            header = section.select_one('.section-header h2')
            if header:
                story.append(Paragraph(header.get_text(strip=True), heading_style))

            table = section.select_one('table')
            if table:
                rows = []
                for tr in table.find_all('tr'):
                    row = [Paragraph(td.get_text(strip=True)[:100], normal_style)
                           for td in tr.find_all(['th', 'td'])]
                    if row:
                        rows.append(row)

                if rows:
                    col_count = len(rows[0]) if rows else 1
                    col_width = (A4[0] - 1.5*inch) / col_count
                    t = Table(rows, colWidths=[col_width] * col_count)
                    t.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#21262d')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#8b949e')),
                        ('FONTSIZE', (0, 0), (-1, -1), 8),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#30363d')),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1),
                         [colors.HexColor('#161b22'), colors.HexColor('#0d1117')]),
                        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                        ('PADDING', (0, 0), (-1, -1), 6),
                    ]))
                    story.append(t)
                    story.append(Spacer(1, 0.1*inch))

        doc.build(story)
        return filepath
    except Exception as e:
        # Fallback: save as HTML with .pdf extension won't work, return error
        raise RuntimeError(f"PDF generation failed: {e}. Install reportlab.")
